server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:queue_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:logs_db}?authSource=${MONGO_AUTH_SOURCE:admin}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_ACCOUNT_ID:seu_account_id_aqui}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY:sua_access_key_aqui}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY:sua_secret_key_aqui}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME:pdf-processor-bucket}
